baseURL = "https://zerolab.org/"
languageCode = "en"
title = "Stuff and nonsense - zerolab"

theme = "zero"

[frontmatter]
  date  = [":filename", ":default"]

[outputs]
  home = ["HTML", "RSS"]

[outputFormats.RSS]
  baseName = "feed"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
