baseURL = "https://zerolab.org/"
languageCode = "en"
title = "Stuff and nonsense - zerolab"

theme = "zero"

[frontmatter]
  date  = [":filename", ":default"]

[outputs]
  home = ["HTML", "RSS"]

[outputFormats.RSS]
  baseName = "feed"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
  [params.author]
    name = 'Dan Braghis'
    email = 'hello+feed@zerolab.org'

[services]
  [services.rss]
    limit = 20
